In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor

In [2]:
train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test.csv')
submission = pd.read_csv('./data/sample_submission.csv')

In [3]:
train['요일'] = train['요일'].map({'월':0, '화':1, '수':2, '목':3, '금':4})
test['요일'] = test['요일'].map({'월':0, '화':1, '수':2, '목':3, '금':4})

x_train = train[['요일', '본사정원수', '본사출장자수', '본사시간외근무명령서승인건수', '현본사소속재택근무자수']]
y1_train = train['중식계']
y2_train = train['석식계']

x_test = test[['요일', '본사정원수', '본사출장자수', '본사시간외근무명령서승인건수', '현본사소속재택근무자수']]

In [4]:
model1 = RandomForestRegressor(n_jobs=-1, random_state=23)
model2 = RandomForestRegressor(n_jobs=-1, random_state=23)

In [5]:
model1.fit(x_train, y1_train)
model2.fit(x_train, y2_train)

RandomForestRegressor(n_jobs=-1, random_state=23)

In [6]:
pred1 = model1.predict(x_test)
pred2 = model2.predict(x_test)

In [7]:
submission['중식계'] = pred1
submission['석식계'] = pred2

In [8]:
submission.to_csv('baseline.csv', index=False)

In [9]:
submission

            일자      중식계     석식계
0   2021-01-27  1064.49  394.79
1   2021-01-28   982.79  384.35
2   2021-01-29   612.17  265.97
3   2021-02-01  1168.84  448.73
4   2021-02-02   992.39  413.49
5   2021-02-03   997.25  430.58
6   2021-02-04   948.72  456.19
7   2021-02-05   605.80  320.50
8   2021-02-08  1174.50  629.70
9   2021-02-09   998.34  462.78
10  2021-02-10   973.65  369.61
11  2021-02-15  1274.00  660.52
12  2021-02-16  1149.69  627.06
13  2021-02-17  1067.82  400.58
14  2021-02-18   865.34  497.33
15  2021-02-19   637.58  331.79
16  2021-02-22  1218.79  614.30
17  2021-02-23   997.07  605.75
18  2021-02-24   745.93  348.61
19  2021-02-25   833.42  486.98
20  2021-02-26   535.01  293.66
21  2021-03-02   987.99  611.34
22  2021-03-03   976.92  419.42
23  2021-03-04   938.94  470.08
24  2021-03-05   572.56  268.93
25  2021-03-08  1281.14  692.89
26  2021-03-09  1216.27  691.46
27  2021-03-10  1024.34  391.02
28  2021-03-11   946.22  478.03
29  2021-03-12   590.91  288.32
30  2021-03-15  1269.51  674.42
31  2021-03-16  1006.96  569.55
32  2021-03-17  1063.57  340.81
33  2021-03-18   870.57  421.46
34  2021-03-19   596.82  282.66
35  2021-03-22  1207.60  596.25
36  2021-03-23   978.67  551.83
37  2021-03-24   910.36  372.84
38  2021-03-25   826.28  396.71
39  2021-03-26   600.31  328.52
40  2021-03-29  1199.74  587.88
41  2021-03-30   984.66  525.20
42  2021-03-31   882.01  371.60
43  2021-04-01   762.93  385.04
44  2021-04-02   611.20  299.63
45  2021-04-05  1194.49  581.83
46  2021-04-06  1012.78  557.42
47  2021-04-07   891.36  337.46
48  2021-04-08   861.89  421.76
49  2021-04-09   613.92  325.84